"""initial

Revision ID: 366bcf1b771e
Revises: 
Create Date: 2020-02-13 15:03:26.674972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366bcf1b771e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
